export const symptoms: Symptom[] = [
  { id: 'symptom_1', name: 'Anxiety And Nervousness' },
  { id: 'symptom_2', name: 'Depression' },
  { id: 'symptom_3', name: 'Shortness Of Breath' },
  { id: 'symptom_4', name: 'Depressive Or Psychotic Symptoms' },
  { id: 'symptom_5', name: 'Sharp Chest Pain' },
  { id: 'symptom_6', name: 'Dizziness' },
  { id: 'symptom_7', name: 'Insomnia' },
  { id: 'symptom_8', name: 'Abnormal Involuntary Movements' },
  { id: 'symptom_9', name: 'Chest Tightness' },
  { id: 'symptom_10', name: 'Palpitations' },
  { id: 'symptom_11', name: 'Irregular Heartbeat' },
  { id: 'symptom_12', name: 'Breathing Fast' },
  { id: 'symptom_13', name: 'Hoarse Voice' },
  { id: 'symptom_14', name: 'Sore Throat' },
  { id: 'symptom_15', name: 'Difficulty Speaking' },
  { id: 'symptom_16', name: 'Cough' },
  { id: 'symptom_17', name: 'Nasal Congestion' },
  { id: 'symptom_18', name: 'Throat Swelling' },
  { id: 'symptom_19', name: 'Diminished Hearing' },
  { id: 'symptom_20', name: 'Lump In Throat' },
  { id: 'symptom_21', name: 'Throat Feels Tight' },
  { id: 'symptom_22', name: 'Difficulty In Swallowing' },
  { id: 'symptom_23', name: 'Skin Swelling' },
  { id: 'symptom_24', name: 'Retention Of Urine' },
  { id: 'symptom_25', name: 'Groin Mass' },
  { id: 'symptom_26', name: 'Leg Pain' },
  { id: 'symptom_27', name: 'Hip Pain' },
  { id: 'symptom_28', name: 'Suprapubic Pain' },
  { id: 'symptom_29', name: 'Blood In Stool' },
  { id: 'symptom_30', name: 'Lack Of Growth' },
  { id: 'symptom_31', name: 'Emotional Symptoms' },
  { id: 'symptom_32', name: 'Elbow Weakness' },
  { id: 'symptom_33', name: 'Back Weakness' },
  { id: 'symptom_34', name: 'Pus In Sputum' },
  { id: 'symptom_35', name: 'Symptoms Of The Scrotum And Testes' },
  { id: 'symptom_36', name: 'Swelling Of Scrotum' },
  { id: 'symptom_37', name: 'Pain In Testicles' },
  { id: 'symptom_38', name: 'Flatulence' },
  { id: 'symptom_39', name: 'Pus Draining From Ear' },
  { id: 'symptom_40', name: 'Jaundice' },
  { id: 'symptom_41', name: 'Mass In Scrotum' },
  { id: 'symptom_42', name: 'White Discharge From Eye' },
  { id: 'symptom_43', name: 'Irritable Infant' },
  { id: 'symptom_44', name: 'Abusing Alcohol' },
  { id: 'symptom_45', name: 'Fainting' },
  { id: 'symptom_46', name: 'Hostile Behavior' },
  { id: 'symptom_47', name: 'Drug Abuse' },
  { id: 'symptom_48', name: 'Sharp Abdominal Pain' },
  { id: 'symptom_49', name: 'Feeling Ill' },
  { id: 'symptom_50', name: 'Vomiting' },
  { id: 'symptom_51', name: 'Headache' },
  { id: 'symptom_52', name: 'Nausea' },
  { id: 'symptom_53', name: 'Diarrhea' },
  { id: 'symptom_54', name: 'Vaginal Itching' },
  { id: 'symptom_55', name: 'Vaginal Dryness' },
  { id: 'symptom_56', name: 'Painful Urination' },
  { id: 'symptom_57', name: 'Involuntary Urination' },
  { id: 'symptom_58', name: 'Pain During Intercourse' },
  { id: 'symptom_59', name: 'Frequent Urination' },
  { id: 'symptom_60', name: 'Lower Abdominal Pain' },
  { id: 'symptom_61', name: 'Vaginal Discharge' },
  { id: 'symptom_62', name: 'Blood In Urine' },
  { id: 'symptom_63', name: 'Hot Flashes' },
  { id: 'symptom_64', name: 'Intermenstrual Bleeding' },
  { id: 'symptom_65', name: 'Hand Or Finger Pain' },
  { id: 'symptom_66', name: 'Wrist Pain' },
  { id: 'symptom_67', name: 'Hand Or Finger Swelling' },
  { id: 'symptom_68', name: 'Arm Pain' },
  { id: 'symptom_69', name: 'Wrist Swelling' },
  { id: 'symptom_70', name: 'Arm Stiffness Or Tightness' },
  { id: 'symptom_71', name: 'Arm Swelling' },
  { id: 'symptom_72', name: 'Hand Or Finger Stiffness Or Tightness' },
  { id: 'symptom_73', name: 'Wrist Stiffness Or Tightness' },
  { id: 'symptom_74', name: 'Lip Swelling' },
  { id: 'symptom_75', name: 'Toothache' },
  { id: 'symptom_76', name: 'Abnormal Appearing Skin' },
  { id: 'symptom_77', name: 'Skin Lesion' },
  { id: 'symptom_78', name: 'Acne Or Pimples' },
  { id: 'symptom_79', name: 'Dry Lips' },
  { id: 'symptom_80', name: 'Facial Pain' },
  { id: 'symptom_81', name: 'Mouth Ulcer' },
  { id: 'symptom_82', name: 'Skin Growth' },
  { id: 'symptom_83', name: 'Eye Deviation' },
  { id: 'symptom_84', name: 'Diminished Vision' },
  { id: 'symptom_85', name: 'Double Vision' },
  { id: 'symptom_86', name: 'Cross-Eyed' },
  { id: 'symptom_87', name: 'Symptoms Of Eye' },
  { id: 'symptom_88', name: 'Pain In Eye' },
  { id: 'symptom_89', name: 'Eye Moves Abnormally' },
  { id: 'symptom_90', name: 'Abnormal Movement Of Eyelid' },
  { id: 'symptom_91', name: 'Foreign Body Sensation In Eye' },
  { id: 'symptom_92', name: 'Irregular Appearing Scalp' },
  { id: 'symptom_93', name: 'Swollen Lymph Nodes' },
  { id: 'symptom_94', name: 'Back Pain' },
  { id: 'symptom_95', name: 'Neck Pain' },
  { id: 'symptom_96', name: 'Low Back Pain' },
  { id: 'symptom_97', name: 'Pain Of The Anus' },
  { id: 'symptom_98', name: 'Pain During Pregnancy' },
  { id: 'symptom_99', name: 'Pelvic Pain' },
  { id: 'symptom_100', name: 'Impotence' },
  { id: 'symptom_101', name: 'Infant Spitting Up' },
  { id: 'symptom_102', name: 'Vomiting Blood' },
  { id: 'symptom_103', name: 'Regurgitation' },
  { id: 'symptom_104', name: 'Burning Abdominal Pain' },
  { id: 'symptom_105', name: 'Restlessness' },
  { id: 'symptom_106', name: 'Symptoms Of Infants' },
  { id: 'symptom_107', name: 'Wheezing' },
  { id: 'symptom_108', name: 'Peripheral Edema' },
  { id: 'symptom_109', name: 'Neck Mass' },
  { id: 'symptom_110', name: 'Ear Pain' },
  { id: 'symptom_111', name: 'Jaw Swelling' },
  { id: 'symptom_112', name: 'Mouth Dryness' },
  { id: 'symptom_113', name: 'Neck Swelling' },
  { id: 'symptom_114', name: 'Knee Pain' },
  { id: 'symptom_115', name: 'Foot Or Toe Pain' },
  { id: 'symptom_116', name: 'Bowlegged Or Knock-Kneed' },
  { id: 'symptom_117', name: 'Ankle Pain' },
  { id: 'symptom_118', name: 'Bones Are Painful' },
  { id: 'symptom_119', name: 'Knee Weakness' },
  { id: 'symptom_120', name: 'Elbow Pain' },
  { id: 'symptom_121', name: 'Knee Swelling' },
  { id: 'symptom_122', name: 'Skin Moles' },
  { id: 'symptom_123', name: 'Knee Lump Or Mass' },
  { id: 'symptom_124', name: 'Weight Gain' },
  { id: 'symptom_125', name: 'Problems With Movement' },
  { id: 'symptom_126', name: 'Knee Stiffness Or Tightness' },
  { id: 'symptom_127', name: 'Leg Swelling' },
  { id: 'symptom_128', name: 'Foot Or Toe Swelling' },
  { id: 'symptom_129', name: 'Heartburn' },
  { id: 'symptom_130', name: 'Smoking Problems' },
  { id: 'symptom_131', name: 'Muscle Pain' },
  { id: 'symptom_132', name: 'Infant Feeding Problem' },
  { id: 'symptom_133', name: 'Recent Weight Loss' },
  { id: 'symptom_134', name: 'Problems With Shape Or Size Of Breast' },
  { id: 'symptom_135', name: 'Underweight' },
  { id: 'symptom_136', name: 'Difficulty Eating' },
  { id: 'symptom_137', name: 'Scanty Menstrual Flow' },
  { id: 'symptom_138', name: 'Vaginal Pain' },
  { id: 'symptom_139', name: 'Vaginal Redness' },
  { id: 'symptom_140', name: 'Vulvar Irritation' },
  { id: 'symptom_141', name: 'Weakness' },
  { id: 'symptom_142', name: 'Decreased Heart Rate' },
  { id: 'symptom_143', name: 'Increased Heart Rate' },
  { id: 'symptom_144', name: 'Bleeding Or Discharge From Nipple' },
  { id: 'symptom_145', name: 'Ringing In Ear' },
  { id: 'symptom_146', name: 'Plugged Feeling In Ear' },
  { id: 'symptom_147', name: 'Itchy Ear(S)' },
  { id: 'symptom_148', name: 'Frontal Headache' },
  { id: 'symptom_149', name: 'Fluid In Ear' },
  { id: 'symptom_150', name: 'Neck Stiffness Or Tightness' },
  { id: 'symptom_151', name: 'Spots Or Clouds In Vision' },
  { id: 'symptom_152', name: 'Eye Redness' },
  { id: 'symptom_153', name: 'Lacrimation' },
  { id: 'symptom_154', name: 'Itchiness Of Eye' },
  { id: 'symptom_155', name: 'Blindness' },
  { id: 'symptom_156', name: 'Eye Burns Or Stings' },
  { id: 'symptom_157', name: 'Itchy Eyelid' },
  { id: 'symptom_158', name: 'Feeling Cold' },
  { id: 'symptom_159', name: 'Decreased Appetite' },
  { id: 'symptom_160', name: 'Excessive Appetite' },
  { id: 'symptom_161', name: 'Excessive Anger' },
  { id: 'symptom_162', name: 'Loss Of Sensation' },
  { id: 'symptom_163', name: 'Focal Weakness' },
  { id: 'symptom_164', name: 'Slurring Words' },
  { id: 'symptom_165', name: 'Symptoms Of The Face' },
  { id: 'symptom_166', name: 'Disturbance Of Memory' },
  { id: 'symptom_167', name: 'Paresthesia' },
  { id: 'symptom_168', name: 'Side Pain' },
  { id: 'symptom_169', name: 'Fever' },
  { id: 'symptom_170', name: 'Shoulder Pain' },
  { id: 'symptom_171', name: 'Shoulder Stiffness Or Tightness' },
  { id: 'symptom_172', name: 'Shoulder Weakness' },
  { id: 'symptom_173', name: 'Arm Cramps Or Spasms' },
  { id: 'symptom_174', name: 'Shoulder Swelling' },
  { id: 'symptom_175', name: 'Tongue Lesions' },
  { id: 'symptom_176', name: 'Leg Cramps Or Spasms' },
  { id: 'symptom_177', name: 'Abnormal Appearing Tongue' },
  { id: 'symptom_178', name: 'Ache All Over' },
  { id: 'symptom_179', name: 'Lower Body Pain' },
  { id: 'symptom_180', name: 'Problems During Pregnancy' },
  { id: 'symptom_181', name: 'Spotting Or Bleeding During Pregnancy' },
  { id: 'symptom_182', name: 'Cramps And Spasms' },
  { id: 'symptom_183', name: 'Upper Abdominal Pain' },
  { id: 'symptom_184', name: 'Stomach Bloating' },
  { id: 'symptom_185', name: 'Changes In Stool Appearance' },
  { id: 'symptom_186', name: 'Unusual Color Or Odor To Urine' },
  { id: 'symptom_187', name: 'Kidney Mass' },
  { id: 'symptom_188', name: 'Swollen Abdomen' },
  { id: 'symptom_189', name: 'Symptoms Of Prostate' },
  { id: 'symptom_190', name: 'Leg Stiffness Or Tightness' },
  { id: 'symptom_191', name: 'Difficulty Breathing' },
  { id: 'symptom_192', name: 'Rib Pain' },
  { id: 'symptom_193', name: 'Joint Pain' },
  { id: 'symptom_194', name: 'Muscle Stiffness Or Tightness' },
  { id: 'symptom_195', name: 'Pallor' },
  { id: 'symptom_196', name: 'Hand Or Finger Lump Or Mass' },
  { id: 'symptom_197', name: 'Chills' },
  { id: 'symptom_198', name: 'Groin Pain' },
  { id: 'symptom_199', name: 'Fatigue' },
  { id: 'symptom_200', name: 'Abdominal Distention' },
  { id: 'symptom_201', name: 'Regurgitation.1' },
  { id: 'symptom_202', name: 'Symptoms Of The Kidneys' },
  { id: 'symptom_203', name: 'Melena' },
  { id: 'symptom_204', name: 'Flushing' },
  { id: 'symptom_205', name: 'Coughing Up Sputum' },
  { id: 'symptom_206', name: 'Seizures' },
  { id: 'symptom_207', name: 'Delusions Or Hallucinations' },
  { id: 'symptom_208', name: 'Shoulder Cramps Or Spasms' },
  { id: 'symptom_209', name: 'Joint Stiffness Or Tightness' },
  { id: 'symptom_210', name: 'Pain Or Soreness Of Breast' },
  { id: 'symptom_211', name: 'Excessive Urination At Night' },
  { id: 'symptom_212', name: 'Bleeding From Eye' },
  { id: 'symptom_213', name: 'Rectal Bleeding' },
  { id: 'symptom_214', name: 'Constipation' },
  { id: 'symptom_215', name: 'Temper Problems' },
  { id: 'symptom_216', name: 'Coryza' },
  { id: 'symptom_217', name: 'Wrist Weakness' },
  { id: 'symptom_218', name: 'Eye Strain' },
  { id: 'symptom_219', name: 'Hemoptysis' },
  { id: 'symptom_220', name: 'Lymphedema' },
  { id: 'symptom_221', name: 'Skin On Leg Or Foot Looks Infected' },
  { id: 'symptom_222', name: 'Allergic Reaction' },
  { id: 'symptom_223', name: 'Congestion In Chest' },
  { id: 'symptom_224', name: 'Muscle Swelling' },
  { id: 'symptom_225', name: 'Pus In Urine' },
  { id: 'symptom_226', name: 'Abnormal Size Or Shape Of Ear' },
  { id: 'symptom_227', name: 'Low Back Weakness' },
  { id: 'symptom_228', name: 'Sleepiness' },
  { id: 'symptom_229', name: 'Apnea' },
  { id: 'symptom_230', name: 'Abnormal Breathing Sounds' },
  { id: 'symptom_231', name: 'Excessive Growth' },
  { id: 'symptom_232', name: 'Elbow Cramps Or Spasms' },
  { id: 'symptom_233', name: 'Feeling Hot And Cold' },
  { id: 'symptom_234', name: 'Blood Clots During Menstrual Periods' },
  { id: 'symptom_235', name: 'Absence Of Menstruation' },
  { id: 'symptom_236', name: 'Pulling At Ears' },
  { id: 'symptom_237', name: 'Gum Pain' },
  { id: 'symptom_238', name: 'Redness In Ear' },
  { id: 'symptom_239', name: 'Fluid Retention' },
  { id: 'symptom_240', name: 'Flu-Like Syndrome' },
  { id: 'symptom_241', name: 'Sinus Congestion' },
  { id: 'symptom_242', name: 'Painful Sinuses' },
  { id: 'symptom_243', name: 'Fears And Phobias' },
  { id: 'symptom_244', name: 'Recent Pregnancy' },
  { id: 'symptom_245', name: 'Uterine Contractions' },
  { id: 'symptom_246', name: 'Burning Chest Pain' },
  { id: 'symptom_247', name: 'Back Cramps Or Spasms' },
  { id: 'symptom_248', name: 'Stiffness All Over' },
  { id: 'symptom_249', name: 'Muscle Cramps, Contractures, Or Spasms' },
  { id: 'symptom_250', name: 'Low Back Cramps Or Spasms' },
  { id: 'symptom_251', name: 'Back Mass Or Lump' },
  { id: 'symptom_252', name: 'Nosebleed' },
  { id: 'symptom_253', name: 'Long Menstrual Periods' },
  { id: 'symptom_254', name: 'Heavy Menstrual Flow' },
  { id: 'symptom_255', name: 'Unpredictable Menstruation' },
  { id: 'symptom_256', name: 'Painful Menstruation' },
  { id: 'symptom_257', name: 'Infertility' },
  { id: 'symptom_258', name: 'Frequent Menstruation' },
  { id: 'symptom_259', name: 'Sweating' },
  { id: 'symptom_260', name: 'Mass On Eyelid' },
  { id: 'symptom_261', name: 'Swollen Eye' },
  { id: 'symptom_262', name: 'Eyelid Swelling' },
  { id: 'symptom_263', name: 'Eyelid Lesion Or Rash' },
  { id: 'symptom_264', name: 'Unwanted Hair' },
  { id: 'symptom_265', name: 'Symptoms Of Bladder' },
  { id: 'symptom_266', name: 'Irregular Appearing Nails' },
  { id: 'symptom_267', name: 'Itching Of Skin' },
  { id: 'symptom_268', name: 'Hurts To Breath' },
  { id: 'symptom_269', name: 'Nailbiting' },
  { id: 'symptom_270', name: 'Skin Dryness, Peeling, Scaliness, Or Roughness' },
  { id: 'symptom_271', name: 'Skin On Arm Or Hand Looks Infected' },
  { id: 'symptom_272', name: 'Skin Irritation' },
  { id: 'symptom_273', name: 'Itchy Scalp' },
  { id: 'symptom_274', name: 'Hip Swelling' },
  { id: 'symptom_275', name: 'Incontinence Of Stool' },
  { id: 'symptom_276', name: 'Foot Or Toe Cramps Or Spasms' },
  { id: 'symptom_277', name: 'Warts' },
  { id: 'symptom_278', name: 'Bumps On Penis' },
  { id: 'symptom_279', name: 'Too Little Hair' },
  { id: 'symptom_280', name: 'Foot Or Toe Lump Or Mass' },
  { id: 'symptom_281', name: 'Skin Rash' },
  { id: 'symptom_282', name: 'Mass Or Swelling Around The Anus' },
  { id: 'symptom_283', name: 'Low Back Swelling' },
  { id: 'symptom_284', name: 'Ankle Swelling' },
  { id: 'symptom_285', name: 'Hip Lump Or Mass' },
  { id: 'symptom_286', name: 'Drainage In Throat' },
  { id: 'symptom_287', name: 'Dry Or Flaky Scalp' },
  { id: 'symptom_288', name: 'Premenstrual Tension Or Irritability' },
  { id: 'symptom_289', name: 'Feeling Hot' },
  { id: 'symptom_290', name: 'Feet Turned In' },
  { id: 'symptom_291', name: 'Foot Or Toe Stiffness Or Tightness' },
  { id: 'symptom_292', name: 'Pelvic Pressure' },
  { id: 'symptom_293', name: 'Elbow Swelling' },
  { id: 'symptom_294', name: 'Elbow Stiffness Or Tightness' },
  { id: 'symptom_295', name: 'Early Or Late Onset Of Menopause' },
  { id: 'symptom_296', name: 'Mass On Ear' },
  { id: 'symptom_297', name: 'Bleeding From Ear' },
  { id: 'symptom_298', name: 'Hand Or Finger Weakness' },
  { id: 'symptom_299', name: 'Low Self-Esteem' },
  { id: 'symptom_300', name: 'Throat Irritation' },
  { id: 'symptom_301', name: 'Itching Of The Anus' },
  { id: 'symptom_302', name: 'Swollen Or Red Tonsils' },
  { id: 'symptom_303', name: 'Irregular Belly Button' },
  { id: 'symptom_304', name: 'Swollen Tongue' },
  { id: 'symptom_305', name: 'Lip Sore' },
  { id: 'symptom_306', name: 'Vulvar Sore' },
  { id: 'symptom_307', name: 'Hip Stiffness Or Tightness' },
  { id: 'symptom_308', name: 'Mouth Pain' },
  { id: 'symptom_309', name: 'Arm Weakness' },
  { id: 'symptom_310', name: 'Leg Lump Or Mass' },
  { id: 'symptom_311', name: 'Disturbance Of Smell Or Taste' },
  { id: 'symptom_312', name: 'Discharge In Stools' },
  { id: 'symptom_313', name: 'Penis Pain' },
  { id: 'symptom_314', name: 'Loss Of Sex Drive' },
  { id: 'symptom_315', name: 'Obsessions And Compulsions' },
  { id: 'symptom_316', name: 'Antisocial Behavior' },
  { id: 'symptom_317', name: 'Neck Cramps Or Spasms' },
  { id: 'symptom_318', name: 'Pupils Unequal' },
  { id: 'symptom_319', name: 'Poor Circulation' },
  { id: 'symptom_320', name: 'Thirst' },
  { id: 'symptom_321', name: 'Sleepwalking' },
  { id: 'symptom_322', name: 'Skin Oiliness' },
  { id: 'symptom_323', name: 'Sneezing' },
  { id: 'symptom_324', name: 'Bladder Mass' },
  { id: 'symptom_325', name: 'Knee Cramps Or Spasms' },
  { id: 'symptom_326', name: 'Premature Ejaculation' },
  { id: 'symptom_327', name: 'Leg Weakness' },
  { id: 'symptom_328', name: 'Posture Problems' },
  { id: 'symptom_329', name: 'Bleeding In Mouth' },
  { id: 'symptom_330', name: 'Tongue Bleeding' },
  { id: 'symptom_331', name: 'Change In Skin Mole Size Or Color' },
  { id: 'symptom_332', name: 'Penis Redness' },
  { id: 'symptom_333', name: 'Penile Discharge' },
  { id: 'symptom_334', name: 'Shoulder Lump Or Mass' },
  { id: 'symptom_335', name: 'Polyuria' },
  { id: 'symptom_336', name: 'Cloudy Eye' },
  { id: 'symptom_337', name: 'Hysterical Behavior' },
  { id: 'symptom_338', name: 'Arm Lump Or Mass' },
  { id: 'symptom_339', name: 'Nightmares' },
  { id: 'symptom_340', name: 'Bleeding Gums' },
  { id: 'symptom_341', name: 'Pain In Gums' },
  { id: 'symptom_342', name: 'Bedwetting' },
  { id: 'symptom_343', name: 'Diaper Rash' },
  { id: 'symptom_344', name: 'Lump Or Mass Of Breast' },
  { id: 'symptom_345', name: 'Vaginal Bleeding After Menopause' },
  { id: 'symptom_346', name: 'Infrequent Menstruation' },
  { id: 'symptom_347', name: 'Mass On Vulva' },
  { id: 'symptom_348', name: 'Jaw Pain' },
  { id: 'symptom_349', name: 'Itching Of Scrotum' },
  { id: 'symptom_350', name: 'Postpartum Problems Of The Breast' },
  { id: 'symptom_351', name: 'Eyelid Retracted' },
  { id: 'symptom_352', name: 'Hesitancy' },
  { id: 'symptom_353', name: 'Elbow Lump Or Mass' },
  { id: 'symptom_354', name: 'Muscle Weakness' },
  { id: 'symptom_355', name: 'Throat Redness' },
  { id: 'symptom_356', name: 'Joint Swelling' },
  { id: 'symptom_357', name: 'Tongue Pain' },
  { id: 'symptom_358', name: 'Redness In Or Around Nose' },
  { id: 'symptom_359', name: 'Wrinkles On Skin' },
  { id: 'symptom_360', name: 'Foot Or Toe Weakness' },
  { id: 'symptom_361', name: 'Hand Or Finger Cramps Or Spasms' },
  { id: 'symptom_362', name: 'Back Stiffness Or Tightness' },
  { id: 'symptom_363', name: 'Wrist Lump Or Mass' },
  { id: 'symptom_364', name: 'Skin Pain' },
  { id: 'symptom_365', name: 'Low Back Stiffness Or Tightness' },
  { id: 'symptom_366', name: 'Low Urine Output' },
  { id: 'symptom_367', name: 'Skin On Head Or Neck Looks Infected' },
  { id: 'symptom_368', name: 'Stuttering Or Stammering' },
  { id: 'symptom_369', name: 'Problems With Orgasm' },
  { id: 'symptom_370', name: 'Nose Deformity' },
  { id: 'symptom_371', name: 'Lump Over Jaw' },
  { id: 'symptom_372', name: 'Sore In Nose' },
  { id: 'symptom_373', name: 'Hip Weakness' },
  { id: 'symptom_374', name: 'Back Swelling' },
  { id: 'symptom_375', name: 'Ankle Stiffness Or Tightness' },
  { id: 'symptom_376', name: 'Ankle Weakness' },
  { id: 'symptom_377', name: 'Neck Weakness' },
];